controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_equipement_import_excel:
    path: /equipement/import-excel
    controller: App\Controller\EquipementController::importExcel
    methods: POST

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: login
